# filename: docker-compose.yml
version: '3.8'

services:
  bitcoind:
    image: ruimarinho/bitcoin-core:24
    container_name: bitcoin-node
    ports:
      - "18443:18443" # RPC port for backend communication
    command:
      -printtoconsole
      -regtest=1
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -rpcuser=admin
      -rpcpassword=admin
      -fallbackfee=0.0002
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin

volumes:
  bitcoin_data:
